# Generated by Django 2.0.9 on 2018-10-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0011_auto_20181023_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_being_annotated', models.BooleanField(default=False)),
                ('last_ann_successful', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
        ),
    ]
