# Generated by Django 2.0.9 on 2018-10-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0010_auto_20181011_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repos', models.CharField(max_length=2000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
        ),
    ]
