# Generated by Django 2.0.9 on 2018-10-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0012_auto_20181024_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepos',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='engine.Task')),
                ('git_repos', models.CharField(max_length=2000)),
            ],
        ),
    ]
